### ISSUE TITLE
pip安装出现错误(error: subprocess-exited-with-error)

### ISSUE THREAD

**Issue by jackforlit** [PeterDing/BaiduPCS-Py#105]
**Describe the bug / 描述 bug**
pip安装出现错误（error: subprocess-exited-with-error）

**To Reproduce / 复现问题**
 pip install BaiduPCS-Py

Cython与[Microsoft C++ Build Tools]已安装。

以下python版本均出现该问题
python 3.7
python 3.8
python 3.11
都出现该问题。

**Screenshots / 问题截图**
Building wheels for collected packages: BaiduPCS-Py, aget, mugen
  Building wheel for BaiduPCS-Py (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for BaiduPCS-Py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Compiling baidupcs_py/common/simple_cipher.pyx because it changed.
      [1/1] Cythonizing baidupcs_py/common/simple_cipher.pyx
      usage: build.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: build.py --help [cmd1 cmd2 ...]
         or: build.py --help-commands
         or: build.py cmd --help

      error: no commands supplied
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-ybl7c2a1/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
        File "/tmp/pip-build-env-ybl7c2a1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-ybl7c2a1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 120, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-ybl7c2a1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 169, in _build
          self._run_build_script(self._package.build_script)
        File "/tmp/pip-build-env-ybl7c2a1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 229, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', 'build.py']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for BaiduPCS-Py
  Building wheel for aget (setup.py) ... done
  Created wheel for aget: filename=aget-0.1.17-py3-none-any.whl size=10142 sha256=fbfd291eae0c97560466769a161480439e0895d697aed35f3d8efd97a8112fe0
  Stored in directory: /home/jackforlit/.cache/pip/wheels/96/67/0c/538a3deb59a1dfe3b300e6a7bf66ddc56dd7288c5d5c5597a1
  Building wheel for mugen (pyproject.toml) ... done
  Created wheel for mugen: filename=mugen-0.6.0-py3-none-any.whl size=17617 sha256=c010a2919820faa3c367f8a76f8b9e92ab657cb65dbf849fb9fa2ec1e92e6452
  Stored in directory: /home/jackforlit/.cache/pip/wheels/00/8b/c0/e1556843a15f55d82fd0163198383817ca46ae21a1bfa0a7b7
Successfully built aget mugen
Failed to build BaiduPCS-Py
ERROR: Could not build wheels for BaiduPCS-Py, which is required to install pyproject.toml-based projects

**Comment by PeterDing** [comment]
已在版本 `v0.7.5` 中修复。

**Comment by tianqingse6** [comment]
用poetry build也会出现这个情况啊

**Comment by mikami-yua** [comment]
这个问题当前在macos中依然是存在的

<img width="731" alt="Image" src="https://github.com/user-attachments/assets/b1195f53-1c43-46b1-8cdc-51dca72cec8a" />
