### ISSUE TITLE
转存分享链接报错 (v0.6.9) System ERROR:

### ISSUE THREAD

**Issue by dollzcx** [PeterDing/BaiduPCS-Py#19]
在windows试了下登录,创建分享,查看文件夹都没问题,但是转存的时候不成功,报 `(v0.6.9) System ERROR:`
命令类似于:
` BaiduPCS-Py save --password  mfgq https://pan.baidu.com/s/1ajltWp8Bu0dXU_NE10eC4g /`
python 是 3.9.2版本, baidupcs-py是0.6.9

**Comment by PeterDing** [comment]
看看 #3 #15 是否能帮到你。

**Comment by PeterDing** [comment]
在 v0.6.10 版，问题已修复。

**Comment by ldj46118** [comment]
比如：A盘分享链接，再转存到A盘的另一个文件夹，为啥提示错误？warning：sharelink ***  has be in ***

**Comment by PeterDing** [comment]
你想要的应该是 `copy` 命令。

**Comment by ldj46118** [comment]
不是，分享的时候，不知道是哪个盘的链接？有可能是A盘，或者B盘，但是转存的时候，都要转存到A盘，有成功的，有不成功的，就会有遗漏。难道save命令有这个限制吗？

**Comment by ldj46118** [comment]
2022-08-10 21:23:42,082 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 838, in mkdir
    file_operators.makedir(api, *remotedirs, show=show)
  File "e:\python\lib\site-packages\baidupcs_py\commands\file_operators.py", line 8, in makedir
    pcs_file = api.makedir(d)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 226, in makedir
    info = self._baidupcs.makedir(directory)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: 31061, message: 文件已经存在

2022-08-10 21:23:42,358 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 838, in mkdir
    file_operators.makedir(api, *remotedirs, show=show)
  File "e:\python\lib\site-packages\baidupcs_py\commands\file_operators.py", line 8, in makedir
    pcs_file = api.makedir(d)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 226, in makedir
    info = self._baidupcs.makedir(directory)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: 31061, message: 文件已经存在

2022-08-10 21:23:42,611 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 838, in mkdir
    file_operators.makedir(api, *remotedirs, show=show)
  File "e:\python\lib\site-packages\baidupcs_py\commands\file_operators.py", line 8, in makedir
    pcs_file = api.makedir(d)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 226, in makedir
    info = self._baidupcs.makedir(directory)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: 31061, message: 文件已经存在

2022-08-10 21:23:42,717 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:23:42,718 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:23:42,781 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:23:42,781 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:23:43,092 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:23:43,093 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:24:28,973 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 1630, in save
    _share.save_shared(
  File "e:\python\lib\site-packages\baidupcs_py\commands\share.py", line 77, in save_shared
    shared_paths = deque(api.shared_paths(shared_url))
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 416, in shared_paths
    info = self._baidupcs.shared_paths(shared_url)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 138, in check
    info = func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\pcs.py", line 790, in shared_paths
    assert self._stoken, "`STOKEN` is not in `cookies`"
AssertionError: `STOKEN` is not in `cookies`

2022-08-10 21:24:29,435 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:24:29,435 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:24:50,147 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 1630, in save
    _share.save_shared(
  File "e:\python\lib\site-packages\baidupcs_py\commands\share.py", line 77, in save_shared
    shared_paths = deque(api.shared_paths(shared_url))
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 416, in shared_paths
    info = self._baidupcs.shared_paths(shared_url)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 138, in check
    info = func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\pcs.py", line 790, in shared_paths
    assert self._stoken, "`STOKEN` is not in `cookies`"
AssertionError: `STOKEN` is not in `cookies`

2022-08-10 21:24:50,529 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:24:50,529 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:25:05,933 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 1630, in save
    _share.save_shared(
  File "e:\python\lib\site-packages\baidupcs_py\commands\share.py", line 77, in save_shared
    shared_paths = deque(api.shared_paths(shared_url))
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 416, in shared_paths
    info = self._baidupcs.shared_paths(shared_url)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 138, in check
    info = func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\pcs.py", line 790, in shared_paths
    assert self._stoken, "`STOKEN` is not in `cookies`"
AssertionError: `STOKEN` is not in `cookies`

2022-08-10 21:25:06,296 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:25:06,296 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:31:09,777 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 1630, in save
    _share.save_shared(
  File "e:\python\lib\site-packages\baidupcs_py\commands\share.py", line 77, in save_shared
    shared_paths = deque(api.shared_paths(shared_url))
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 416, in shared_paths
    info = self._baidupcs.shared_paths(shared_url)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 138, in check
    info = func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\pcs.py", line 790, in shared_paths
    assert self._stoken, "`STOKEN` is not in `cookies`"
AssertionError: `STOKEN` is not in `cookies`

2022-08-10 21:31:10,319 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:31:10,319 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:46:47,895 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 838, in mkdir
    file_operators.makedir(api, *remotedirs, show=show)
  File "e:\python\lib\site-packages\baidupcs_py\commands\file_operators.py", line 8, in makedir
    pcs_file = api.makedir(d)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 226, in makedir
    info = self._baidupcs.makedir(directory)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: 31061, message: 文件已经存在

2022-08-10 21:46:48,148 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:46:48,149 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:47:01,919 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 1630, in save
    _share.save_shared(
  File "e:\python\lib\site-packages\baidupcs_py\commands\share.py", line 75, in save_shared
    api.access_shared(shared_url, password, show_vcode=show_vcode)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 398, in access_shared
    raise err
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 380, in access_shared
    self._baidupcs.access_shared(shared_url, password, vcode_str, vcode)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: -62, message: 可能需要输入验证码

2022-08-10 21:47:02,258 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:47:02,258 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:48:25,826 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 838, in mkdir
    file_operators.makedir(api, *remotedirs, show=show)
  File "e:\python\lib\site-packages\baidupcs_py\commands\file_operators.py", line 8, in makedir
    pcs_file = api.makedir(d)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 226, in makedir
    info = self._baidupcs.makedir(directory)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: 31061, message: 文件已经存在

2022-08-10 21:48:26,076 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:48:26,076 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:48:26,343 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "e:\python\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "e:\python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "e:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 466, in useradd
    account = Account.from_bduss(bduss, cookies=cookies, account_name=account_name)
  File "e:\python\lib\site-packages\baidupcs_py\app\account.py", line 45, in from_bduss
    user = api.user_info()
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 477, in user_info
    info = self._baidupcs.user_info()
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 138, in check
    info = func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\pcs.py", line 915, in user_info
    return resp.json()
  File "e:\python\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-08-10 21:48:26,826 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:48:26,826 | DEBUG | app: `app`: _teardown: end
2022-08-10 21:48:41,133 | DEBUG | app: `app`: BaiduPCSError: Traceback (most recent call last):
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 118, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 176, in wrap
    return func(*args, **kwargs)
  File "e:\python\lib\site-packages\baidupcs_py\app\app.py", line 1630, in save
    _share.save_shared(
  File "e:\python\lib\site-packages\baidupcs_py\commands\share.py", line 75, in save_shared
    api.access_shared(shared_url, password, show_vcode=show_vcode)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 398, in access_shared
    raise err
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\api.py", line 380, in access_shared
    self._baidupcs.access_shared(shared_url, password, vcode_str, vcode)
  File "e:\python\lib\site-packages\baidupcs_py\baidupcs\errors.py", line 152, in check
    raise err
baidupcs_py.baidupcs.errors.BaiduPCSError: error_code: -62, message: 可能需要输入验证码

2022-08-10 21:48:41,457 | DEBUG | app: `app`: _teardown: start
2022-08-10 21:48:41,457 | DEBUG | app: `app`: _teardown: end
