### ISSUE TITLE
(v0.6.16) System ERROR: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by Frozen5293** [PeterDing/BaiduPCS-Py#35]
As the title says , when I  downloading.

**Comment by PeterDing** [comment]
请务必确保你的描述依从 [bug issus 模板](https://github.com/PeterDing/BaiduPCS-Py/blob/master/.github/ISSUE_TEMPLATE/bug-report---bug---.md)，不然无法找到问题。

**Comment by Frozen5293** [comment]
[![001.png](https://img1.picloli-1.xyz/2021/04/15/001.png)](https://picloli.com/image/uPEw7)

- BaiduPCS-Py Version: v0.6.16
- Python Version： 3.7.7
- OS：Windows10 2004

复现方式：

​	1.添加用户

​	2.下载

​	3.问题出现

**Comment by PeterDing** [comment]
运行日志：

1. 删除 `~/.baidupcs-py/running.log`，如果存在。
2. 在问题发生的命令前加入环境变量 `LOG_LEVEL=DEBUG`。
  例如：`LOG_LEVEL=DEBUG BaiduPCS-Py upload /abc /`
  在 Windows 上，设置环境变量如下：
  ```
  set LOG_LEVEL=DEBUG
  ```
  然后再运行出现问题的命令。
3. 在问题出现后，贴出 `~/.baidupcs-py/running.log` 中的内容。

**Comment by Frozen5293** [comment]
2021-04-15 13:44:53,533 | DEBUG | download: `download`: sifters: [], recursive: False, from_index: 0, downloader: Downloader.me, downloadparams: DownloadParams(chunk_size='1048576', concurrency=5, quiet=False), out_cmd: False, has encrypt_password: False
2021-04-15 13:44:53,533 | DEBUG | download: `download`: remotepaths should be uniq 1 == 1
2021-04-15 13:44:56,136 | DEBUG | app: `app`: _exit_progress_bar: stop progress bar
2021-04-15 13:44:56,157 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\app\app.py", line 117, in wrap
    return func(*args, **kwargs)
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\app\app.py", line 175, in wrap
    return func(*args, **kwargs)
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\app\app.py", line 984, in download
    encrypt_password=encrypt_password,
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\commands\download.py", line 405, in download
    encrypt_password=encrypt_password,
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\commands\download.py", line 311, in download_file
    encrypt_password=encrypt_password,
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\commands\download.py", line 84, in download
    encrypt_password=encrypt_password,
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\commands\download.py", line 175, in _me_download
    length = len(meDownloader)
  File "c:\users\USR\appdata\local\programs\python\python37-32\lib\site-packages\baidupcs_py\common\io.py", line 1051, in __len__
    return len(self._auto_decrypt_request)
OverflowError: cannot fit 'int' into an index-sized integer

2021-04-15 13:44:56,657 | DEBUG | app: `app`: _teardown: start
2021-04-15 13:44:56,657 | DEBUG | app: `app`: _teardown: end

running.log

**Comment by PeterDing** [comment]
你运行的 python3 应该是 32位的吧。
32位的 python3 在处理一些大数的时候，可能有一些问题，见 https://github.com/boto/boto3/issues/2457

你可以换用 64位的 python3 试试。 比如 https://www.python.org/ftp/python/3.9.4/python-3.9.4-amd64.exe

**Comment by PeterDing** [comment]
python 的 int 数据应该不会有大小限制。出这个错，我目前也不太明白。但是换 64位的试试吧

**Comment by PeterDing** [comment]
找到这个 https://bugs.python.org/issue21444#msg217957

**Comment by Frozen5293** [comment]
但是之前运行过一次，是可以使用的，这不是很奇怪吗

**Comment by PeterDing** [comment]
出现报错的文件 `是.7` 应该大于或等于 2G 吧。
好像 python 32位的 `__len__` 方法返回结果大于 2G 就是这个错。

你可以自己检查一下：
用python 32 位运行下面的代码：

```python
class A:
    def __len__(self):
        return 1 << 33

a = A()
len(a)
```

应该会报 `OverflowError: cannot fit 'int' into an index-sized integer`

**Comment by Frozen5293** [comment]
应该就是这个问题了
之前下载的就是小于2G的，这次几个测试都是大于的
