### ISSUE TITLE
下载文件时报错PermissionError: [WinError 32]

### ISSUE THREAD

**Issue by bear-zd** [PeterDing/BaiduPCS-Py#40]
首先感谢你们的代码，让我可以实现网盘文件同步功能。
**Prerequisites / 报告前提**
按照readme所给出的使用方法我进行操作。
**Describe the bug / 描述 bug**
在使用的过程中，成功的添加用户并能进行目录操作，但当我尝试使用 **“BaiduPCS-Py download wordcount_v2.xlsx”** 指令下载云盘文件时出现了权限错误问题：PermissionError: [WinError 32]，详细内容内容如下
**To Reproduce / 复现问题**
1.添加用户，且使用 **“BaiduPCS-Py who”** 可以查看到正确的用户
2. 通过目录操作进入需要下载的文件目录
3. 使用 **”BaiduPCS-Py download wordcount_v2.xlsx“** 下载“wordcount_v2.xlsx"成功
4. 问题出现：
   报错如下：
‘’‘
exception calling callback for <Future at 0x151e400e1d0 state=finished returned NoneType>
Traceback (most recent call last):
  File "C:\Users\a8275\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 557, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'wordcount_v2.xlsx.tmp' -> 'wordcount_v2.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a8275\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "c:\users\a8275\desktop\useless thing\computer network\socket\env\lib\site-packages\baidupcs_py\commands\download.py", line 159, in _wrap_done_callback
    done_callback(fut)
  File "c:\users\a8275\desktop\useless thing\computer network\socket\env\lib\site-packages\baidupcs_py\commands\download.py", line 77, in done_callback
    shutil.move(localpath_tmp, localpath)
  File "C:\Users\a8275\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 572, in move
    os.unlink(src)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'wordcount_v2.xlsx.tmp'
’‘’
**错误截图**
![image](https://user-images.githubusercontent.com/58643709/116092816-b5e89f00-a6d8-11eb-8260-099a466e5bc4.png)

**Envrionment / 运行环境**
 - OS: Windows10
 - Python:Python3.7
 - BaiduPCS-Py Version:0.6.9

**Comment by PeterDing** [comment]
目前没有 Windows 10 环境，但我尝试修复了，试试最新版本 v0.6.18，看看还有没有问题。

**Comment by bear-zd** [comment]
谢谢，现在文件能成功下载了！
![image](https://user-images.githubusercontent.com/58643709/116107101-4d53ef00-a6e5-11eb-81c8-af40d2802a07.png)
