### ISSUE TITLE
下载没速度

### ISSUE THREAD

**Issue by cryzlasm** [PeterDing/BaiduPCS-Py#5]
## 下载命令

```bash
(Baiduyun) ➜  test BaiduPCS-Py download ./1 -R -o ./ --no-decrypt
(v0.5.1) System ERROR: AutoDecryptRequest - Server does not support `Range` head
⠦ 1/图包.part1.rar.tmp ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0% • 0/100 bytes • ? • -:--:--

```

## 用户配置
```bash
(Baiduyun) ➜  samples BaiduPCS-Py ul
 Index   Recent   User Id      User Name   Quota           SVIP   VIP   pwd 
────────────────────────────────────────────────────────────────────────────
 1       ✔        3225735228   Mh00mg3     461.3 GB/6 TB   ✔      ✔     /   
```

**Comment by cryzlasm** [comment]
```bash
(Baiduyun) ➜  samples BaiduPCS-Py ls
/
  Path                                                       
─────────────────────────────────────────────────────────────
d 000                                                        
d 1                                                          
d 1.31                                                       
d 2                                                          
d Adobe常用软件                                              
d Borderlands.3.Designers.Cut-CODEX                          
d D.L.Hellraid                                               
d deadrising3-jisu                                           
d Fate HF 第一章BD                                         
```

这是部分目录

**Comment by PeterDing** [comment]
@cryzlasm 我无法复现这个 error。等我把 log 模块写完就可以 debug 了。请等一等 😆

**Comment by cryzlasm** [comment]
那就等一下吧,  估计是因为我登录的共享的 "炒鸡 VIP"  然后这时候被顶了吧, 

因为后续会有  
```bash
(Baiduyun) ➜  samples BaiduPCS-Py d ./1 -R 
(v0.5.1) System ERROR: 'list'
(Baiduyun) ➜  samples BaiduPCS-Py ls       
(v0.5.1) System ERROR: 'list'

```

**Comment by PeterDing** [comment]
@cryzlasm v0.5.2 版加入了 debug 模式。用下面的命令开启。

```
LOG_LEVEL=DEBUG BaiduPCS-Py {cmd} ...
```

运行结束后，请将 `~/.baidupcs-py/running.log` 对应的 log 贴出来。

为了 debug 方便，请只输入单个远端路径。

**Comment by cryzlasm** [comment]
可能还是 共享炒鸡VIP 的问题

```bash
(BaiduPCS) ➜  downloads BaiduPCS-Py d -R 111112222
(v0.5.2) System ERROR: AutoDecryptRequest - Server does not support `Range` head. Response content:
b'{"error_code":31326,"error_msg":"user is not authorized, hitcode:117","error_info":"","request_id":720140943676925927}'
⠋ 111112222/1250FFZWG/1250FFZWG.7z.tmp ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

```bash
b'{"error_code":31326,"error_msg":"user is not authorized, hitcode:117","error_info":"","request_id":720140943676925927}'
```

**Comment by cryzlasm** [comment]
running.log 是空的 

```bash
(BaiduPCS) ➜  .baidupcs-py BaiduPCS-Py
Usage: BaiduPCS-Py [OPTIONS] COMMAND [ARGS]...

  BaiduPCS App v0.5.2

  如果第一次使用，你需要运行 `BaiduPCS-Py useradd` 添加 `bduss` 和 `cookies`。
  如何获取 `bduss` 和 `cookies` 见 https://github.com/PeterDing/BaiduPCS-Py#%E6%B7%BB%E5%8A%A0%E7%94%A8%E6%88%B7
  用 `BaiduPCS-Py {command} --help` 查看具体的用法。
```


对了, 有空加个 Version 命令吧

**Comment by cryzlasm** [comment]
上边那个应该是我没设置 那个DEBUG

```bash
2021-01-31 14:49:03,691 | DEBUG | download: `download`: sifters: [], recursive: True, from_index: 0, downloader: Downloader.me, downloadparams: DownloadParams(chunk_size='1048576', concurrency=5, quiet=False), out_cmd: False, has encrypt_key: False
2021-01-31 14:49:03,691 | DEBUG | download: `download`: remotepaths should be uniq 1 == 1
2021-01-31 14:49:04,504 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/app/app.py", line 83, in wrap
    return func(*args, **kwargs)
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/app/app.py", line 768, in download
    _download(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 405, in download
    download_dir(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 338, in download_dir
    download_dir(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 327, in download_dir
    download_file(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 301, in download_file
    downloader.download(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 77, in download
    self._me_download(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 174, in _me_download
    length = len(meDownloader)
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/common/io.py", line 848, in __len__
    return len(self._auto_decrypt_request)
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/common/io.py", line 766, in __len__
    return self.remote_len - self._total_head_len
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/common/io.py", line 746, in remote_len
    raise IOError(
OSError: AutoDecryptRequest - Server does not support `Range` head. Response content: b'{"error_code":31326,"error_msg":"user is not authorized, hitcode:117","error_info":"","request_id":720212905104830535}'

2021-01-31 14:49:08,020 | DEBUG | app: `app`: handle_signal: 2
2021-01-31 14:49:10,555 | DEBUG | download: `download`: sifters: [], recursive: True, from_index: 0, downloader: Downloader.me, downloadparams: DownloadParams(chunk_size='1048576', concurrency=5, quiet=False), out_cmd: False, has encrypt_key: False
2021-01-31 14:49:10,556 | DEBUG | download: `download`: remotepaths should be uniq 1 == 1
2021-01-31 14:49:11,082 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/app/app.py", line 83, in wrap
    return func(*args, **kwargs)
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/app/app.py", line 768, in download
    _download(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 405, in download
    download_dir(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 338, in download_dir
    download_dir(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 327, in download_dir
    download_file(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 301, in download_file
    downloader.download(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 77, in download
    self._me_download(
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/commands/download.py", line 174, in _me_download
    length = len(meDownloader)
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/common/io.py", line 848, in __len__
    return len(self._auto_decrypt_request)
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/common/io.py", line 766, in __len__
    return self.remote_len - self._total_head_len
  File "/root/python_env/BaiduPCS/lib/python3.8/site-packages/baidupcs_py/common/io.py", line 746, in remote_len
    raise IOError(
OSError: AutoDecryptRequest - Server does not support `Range` head. Response content: b"[10.134.41.155:2010][E1002]Fail to find method on `/file/10b8137ceib7037fb3eb9a9fbabe6e82'\n"

2021-01-31 14:49:33,058 | DEBUG | app: `app`: handle_signal: 2

```

**Comment by PeterDing** [comment]
@cryzlasm 应该就是你的帐号问题。

version (v0.5.2) 已经显示在 `BaiduPCS-Py --help` 中
