### ISSUE TITLE
System ERROR: AutoDecryptRequest - Request Error

### ISSUE THREAD

**Issue by jingyuxin98** [PeterDing/BaiduPCS-Py#59]
本来都可以运行的 但是今天发现下载的时候报错: (v0.6.21) System ERROR: AutoDecryptRequest - Request Error
环境: Ubuntu 18.4, IP是在美国 之前都是下的好好的突然不行了
同一个账户我用国内的机器就可以

**Comment by PeterDing** [comment]
你升级到最新版试试。

**Comment by jingyuxin98** [comment]
> 你升级到最新版试试。

还是不行，同样的命令在国内的服务器就可以跑。但是美国的服务器账户还可以操作文件 就是下载不了文件

**Comment by jingyuxin98** [comment]
日志文件:


2021-07-15 02:45:19,328 | DEBUG | download: `download`: sifters: [], recursive: True, from_index: 0, downloader: Downloader.me, downloadparams: DownloadParams(chunk_size='50m', concurrency=5, quiet=False), out_cmd: False, has encrypt_password: False
2021-07-15 02:45:19,329 | DEBUG | download: `download`: remotepaths should be uniq 1 == 1
2021-07-15 02:45:23,501 | DEBUG | app: `app`: _exit_progress_bar: stop progress bar
2021-07-15 02:45:23,510 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/mnt/home/jingyu/.conda/envs/gluoncv/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by jingyuxin98** [comment]
刚刚弄了下 发现不能用--recursive 但是单独下文件就行

**Comment by jalatls** [comment]
请问解决了吗
