### ISSUE TITLE
异地登录限制

### ISSUE THREAD

**Issue by boan-anbo** [PeterDing/BaiduPCS-Py#61]
作者你好！感谢开发这么完善的库。我遇到的问题是在__挂美国VPN的时候一切正常__，但__用德国IP就无法在Python代码里登陆__（命令行模式不影响），会出错如下：
```
Traceback (most recent call last):
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Bo\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
请问是什么原因呢？已经换过Cookies，浏览器重新登陆等等（浏览器上在哪个IP登陆都没有问题）。非常感谢！

**Comment by PeterDing** [comment]
应该是和 #53 一样的问题。
试试用 https://github.com/qjfoidnh/BaiduPCS-Go/issues/93 提到的方法。

**Comment by boan-anbo** [comment]
> 应该是和 #53 一样的问题。
> 试试用 [qjfoidnh/BaiduPCS-Go#93](https://github.com/qjfoidnh/BaiduPCS-Go/issues/93) 提到的方法。

非常感谢！我试试，不好意思之前看最后一句错误信息不一样以为是不同的issue，抱歉

**Comment by OnePerson2020** [comment]
请问提示(v0.4.0) System ERROR: 'Progress' object has no attribute '_started' 怎么解决？
![image](https://user-images.githubusercontent.com/87254401/137897907-b63e2cf5-a722-41b8-b23a-3f606a891236.png)
