### ISSUE TITLE
windows下出现编码问题

### ISSUE THREAD

**Issue by fxsome** [PeterDing/BaiduPCS-Py#7]
pip安装后，BaiduPCS-Py --help
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\BaiduPCS-Py.exe\__main__.py", line 4, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\baidupcs_py\app\__init__.py", line 2, in <module>
    from baidupcs_py.app.app import app as _app
  File "c:\programdata\anaconda3\lib\site-packages\baidupcs_py\app\app.py", line 49, in <module>
    from baidupcs_py.commands.server import start_server
  File "c:\programdata\anaconda3\lib\site-packages\baidupcs_py\commands\server.py", line 32, in <module>
    _html_tempt: Template = Template((Path(__file__).parent / "index.html").open().read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 16484: illegal multibyte sequence
```

**Comment by PeterDing** [comment]
@fxsome 在 v0.5.10，设置了默认编码为 utf-8。试试看。

**Comment by PeterDing** [comment]
在 windows 2012 server 上测试没问题了。
