### ISSUE TITLE
System ERROR: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by UVJkiNTQ** [PeterDing/BaiduPCS-Py#70]
**Describe the bug / 描述 bug**
请清楚的描述你遇到的问题。

于Armv7板子上下载4.82G文件出现溢出异常。
报错信息 System ERROR: cannot fit 'int' into an index-sized integer

**Envrionment / 运行环境**
 - OS:  Archlinux Arm
 - Python Python 3.9
 - BaiduPCS-Py Version v0.6.27

2021-09-21 04:36:47,132 | DEBUG | download: `download`: sifters: [], recursive: True, from_index: 0, downloader: Downloader.me, downloadparams: DownloadParams(concurrency=5, chunk_size='5242880', quiet=False), out_cmd: False, has encrypt_password: False
2021-09-21 04:36:47,134 | DEBUG | download: `download`: remotepaths should be uniq 1 == 1
2021-09-21 04:36:59,026 | DEBUG | app: `app`: _exit_progress_bar: stop progress bar
2021-09-21 04:37:00,463 | DEBUG | app: `app`: System Error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/baidupcs_py/app/app.py", line 117, in wrap
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/baidupcs_py/app/app.py", line 175, in wrap
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/baidupcs_py/app/app.py", line 972, in download
    _download(
  File "/usr/lib/python3.9/site-packages/baidupcs_py/commands/download.py", line 414, in download
    download_dir(
  File "/usr/lib/python3.9/site-packages/baidupcs_py/commands/download.py", line 332, in download_dir
    download_file(
  File "/usr/lib/python3.9/site-packages/baidupcs_py/commands/download.py", line 306, in download_file
    downloader.download(
  File "/usr/lib/python3.9/site-packages/baidupcs_py/commands/download.py", line 79, in download
    self._me_download(
  File "/usr/lib/python3.9/site-packages/baidupcs_py/commands/download.py", line 176, in _me_download
    length = len(meDownloader)
  File "/usr/lib/python3.9/site-packages/baidupcs_py/common/io.py", line 1053, in __len__
    return len(self._auto_decrypt_request)
OverflowError: cannot fit 'int' into an index-sized integer

2021-09-21 04:37:16,954 | DEBUG | app: `app`: _teardown: start
2021-09-21 04:37:16,968 | DEBUG | app: `app`: _teardown: end

补充:
使用ag下载正常，换x86平台使用me下载正常。

**Comment by PeterDing** [comment]
在32位的系统，使用 `me` 下载大于 4G 的文件都会报 `OverflowError`。见 #35
